export const APP_DEVICE_READY = 'APP_DEVICE_READY';
export const APP_LOCATION_CHANGE = 'APP_LOCATION_CHANGE';
export const APP_LOCATION_REQUEST = 'APP_LOCATION_REQUEST';
export const APP_LOCATION_WATCH_CHANGE = 'APP_LOCATION_WATCH_CHANGE';
export const APP_LOCATION_WATCH_CLEAR = 'APP_LOCATION_WATCH_CLEAR';
export const APP_ALERT_SHOW = 'APP_ALERT_SHOW';
export const APP_ALERT_DISMISS = 'APP_ALERT_DISMISS';